version: '3.9'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
    ports:
      - 8080:80
